[[hooks]]
stage = "pre_build"
command = "npx"
command_arguments = ["--yes", "@tailwindcss/cli", "-i", "style/tailwind.css", "-o", "style/output.css", "--minify"]

[[proxy]]
rewrite = "/api/"
backend = "http://127.0.0.1:19697/"
